import React from 'react';

const Blog = () => {
    return (
        <div className='container my-5'>
            <h1>Differences Between JavaScript vs Node JS</h1>
            <p style={{ textAlign: 'justify' }}>JavaScript is a simple programming language that runs in any browser JavaScript Engine.Node js is an interpreter or running environment for a JavaScript programming language that holds many excesses, it requires libraries that can easily be accessed from JavaScript programming for better use.Javascript can only be run in the browsers.
                We can run Javascript outside the browser with the help of NodeJS.	Javascript is capable enough to add HTML and play with the DOM.Nodejs does not have capability to add HTML tags.Some of the javascript frameworks are RamdaJS, TypedJS, etc.Some of the Nodejs modules are Lodash, express etc. These modules are to be imported from npm.
            </p>
            <h1>difference between sql and nosql database</h1>
            <p style={{ textAlign: 'justify' }}>SQL,These databases have fixed or static or predefined schema
                NOSQL They have dynamic schema
                SQL databases are table-based, while NoSQL databases are document, key-value, graph, or wide-column stores.SQL databases are relational, NoSQL databases are non-relational.SQL databases use structured query language and have a predefined schema. NoSQL databases have dynamic schemas for unstructured data.SQL databases are better for multi-row transactions, while NoSQL is better for unstructured data like documents or JSON.
            </p>
            <h1>what is the purpose of jwt and how does it work</h1>
            <p style={{ textAlign: 'justify' }}>
                JSON Web Tokens (JWT) are tokens generated by the server upon user authentication on a web application, and then sent to the client (usually a browser).

                These tokens are then sent on every HTTP request, which allows the server to authenticate the user.
                When a server receives a JWT, it can guarantee the data it contains can be trusted because it’s signed by the source. No middleman can modify a JWT once it’s sent.JWTs can be encrypted, but they are typically encoded & signed.  We will be focusing on Signed JWTs. The purpose of Signed JWT is not to hide the data but to ensure the authenticity of the data. And that is why it’s highly recommended to use HTTPS with Signed JWTs.
            </p>
        </div>
    );
};

export default Blog;